# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.





class TimerClick(QtCore.QThread):
    sin_out = QtCore.pyqtSignal()

    def __init__(self):
        super(TimerClick, self).__init__()
        self.w = True

    def run(self) -> None:
        while self.w:
            if time.gmtime().tm_sec % 10 == 0:
                self.sin_out.emit()
                self.sleep(1)

    def __del__(self):
        self.w = False

